enum EnemyType {
  GHOST1 = 'GHOST1',
  GHOST2 = 'GHOST2',
  GHOST3 = 'GHOST3',
  GHOST_BOSS1 = 'GHOST_BOSS1',
  GHOST_BOSS2 = 'GHOST_BOSS2',
  GHOST_SWARM = 'GHOST_SWARM',
  ZOMBIE = 'ZOMBIE',
  POO = 'POO',
  BAT = 'BAT',
  BAT_SWARM = 'BAT_SWARM'
}

export default EnemyType
