enum Treasure {
  POWERUP = 'POWERUP',
  EXISTING_WEAPON = 'EXISTING_WEAPON',
  EXISTING_ANY = 'EXISTING_ANY',
  FILLER = 'FILLER',
  RANDOM = 'RANDOM',
  FIXED = 'FIXED',
  EVOLUTION = 'EVOLUTION'
}

export default Treasure
